import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7F8FA' },
  planContent: { padding: 16, paddingBottom: 8, paddingTop: 20 },
  dayScroll: { flex: 1 },
  dayScrollContent: { paddingBottom: 18, paddingHorizontal: 16, paddingTop: 4 },
  planTopBar: { alignItems: 'center', flexDirection: 'row', height: 30, justifyContent: 'space-between' },
  topBarLabel: { color: '#6B7280', fontSize: 11, fontWeight: '700', letterSpacing: 1.4 },
  settingsButton: { alignItems: 'center', borderRadius: 10, height: 38, justifyContent: 'center', width: 38 },
  settingsIcon: { color: '#4B5563', fontSize: 20, fontWeight: '400', lineHeight: 25 },
  planHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
    marginTop: 4,
  },
  titleButton: { alignItems: 'center', borderRadius: 12, paddingHorizontal: 10 },
  planTitle: { color: '#111827', fontSize: 20, flexShrink: 1, fontWeight: '700', letterSpacing: -0.5 },
  navigation: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end' },
  arrowButton: { alignItems: 'center', borderRadius: 12, height: 52, justifyContent: 'center', width: 52 },
  arrow: { color: '#4B5563', fontSize: 30, fontWeight: '300', lineHeight: 42 },
  navigationLabel: { color: '#2563EB', fontSize: 12, fontWeight: '700' },
  pressedButton: { backgroundColor: '#EFF6FF' },
  disabledButton: { opacity: 0.45 },
  disabledText: { color: '#A9B0B8' },
  weekList: { gap: 14 },
  dayCard: { backgroundColor: '#FFFFFF', borderColor: '#E5E7EB', borderRadius: 14, borderWidth: 1, padding: 13 },
  todayDayCard: { borderLeftColor: '#60A5FA', borderLeftWidth: 3 },
  dayHeading: {
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 11,
    marginHorizontal: -13,
    marginTop: -13,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  todayDayHeading: { backgroundColor: '#EAF2FF' },
  dayName: { color: '#111827', fontSize: 15, fontWeight: '700' },
  dayCount: { color: '#6B7280', fontSize: 12, fontWeight: '500' },
  dayDate: {
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  emptyDay: {
    alignItems: 'center',
    backgroundColor: '#FCFCFD',
    borderColor: '#D1D5DB',
    borderRadius: 10,
    borderStyle: 'dashed',
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 58,
    padding: 10,
    position: 'relative',
  },
  emptyDayDropTarget: { backgroundColor: '#EFF6FF', borderColor: '#60A5FA', borderWidth: 1.5 },
  emptyDayText: { color: '#6B7280', fontSize: 12 },
  emptyDayDropIcon: { color: '#2563EB', fontSize: 18, fontWeight: '500', lineHeight: 18 },
  emptyDayDropText: { color: '#2563EB', fontSize: 13, fontWeight: '700', marginTop: 2 },
  addTodoButton: {
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    borderColor: '#DBEAFE',
    borderRadius: 9,
    borderWidth: 1,
    height: 26,
    marginLeft: 7,
    marginTop: 8,
    justifyContent: 'center',
    width: 26,
  },
  addTodoIcon: { color: '#2563EB', fontSize: 17, fontWeight: '400', lineHeight: 20 },
  dayLoader: { minHeight: 42 },
  errorState: { alignItems: 'center', backgroundColor: '#FEF2F2', borderRadius: 10, minHeight: 58, justifyContent: 'center', padding: 8 },
  errorStateText: { color: '#B04C4C', fontSize: 12, marginBottom: 5 },
  retryButton: { borderRadius: 8, minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 },
  retryButtonText: { color: '#2563EB', fontSize: 12, fontWeight: '700' },
  todoList: { gap: 5, position: 'relative' },
  draggableTodo: { zIndex: 1 },
  draggingTodo: {
    elevation: 6,
    opacity: 0.58,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    zIndex: 10,
  },
  dropIndicator: {
    alignItems: 'center',
    backgroundColor: '#DBEAFE',
    borderRadius: 7,
    flexDirection: 'row',
    height: 14,
    left: 4,
    paddingHorizontal: 4,
    position: 'absolute',
    right: 4,
    transform: [{ translateY: -7 }],
    zIndex: 2,
  },
  dropIndicatorDot: { backgroundColor: '#3B82F6', borderRadius: 4, height: 7, width: 7 },
  dropIndicatorLine: { backgroundColor: '#3B82F6', borderRadius: 2, flex: 1, height: 2 },
  todoRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#F3F4F6',
    borderRadius: 9,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 40,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  pressedTodoRow: { opacity: 0.78 },
  todoToggle: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  completedTodoRow: { backgroundColor: '#F3F4F6', borderColor: '#F3F4F6' },
  checkbox: {
    alignItems: 'center',
    borderColor: '#D1D5DB',
    borderRadius: 7,
    borderWidth: 1.5,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  checkedBox: { backgroundColor: '#3B82F6', borderColor: '#3B82F6' },
  checkmark: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  completedText: { color: '#9CA3AF', textDecorationLine: 'line-through' },
  todoTime: { color: '#6B7280', flexShrink: 0, fontSize: 12, fontWeight: '600', width: 38 },
  todoTitle: { color: '#1F2937', flex: 1, flexShrink: 1, fontSize: 14, lineHeight: 19 },
  todoTagIcon: { color: '#6B7280', fontSize: 15, fontWeight: '500', textAlign: 'center', width: 20 },
  modalRoot: { backgroundColor: 'rgba(22, 34, 53, 0.48)', flex: 1, justifyContent: 'flex-end' },
  modalScroll: { flex: 1 },
  modalScrollContent: { flexGrow: 1, justifyContent: 'flex-end' },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 18,
    paddingBottom: 26,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '88%',
    padding: 18,
    paddingBottom: 26,
  },
  infoTitleBlock: { flex: 1 },
  infoScroll: { flexShrink: 1 },
  infoContent: { paddingBottom: 4 },
  infoLead: { color: '#374151', fontSize: 16, lineHeight: 24, marginBottom: 6 },
  infoSectionTitle: { color: '#111827', fontSize: 15, fontWeight: '700', marginTop: 18 },
  infoText: { color: '#4B5563', fontSize: 14, lineHeight: 21, marginTop: 6 },
  modalHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  modalTitle: { color: '#111827', fontSize: 22, fontWeight: '700', marginTop: 5 },
  closeButton: { alignItems: 'center', backgroundColor: '#F3F4F6', borderRadius: 20, height: 40, justifyContent: 'center', width: 40 },
  closeText: { color: '#4B5563', fontSize: 24, fontWeight: '300', lineHeight: 30 },
  fieldLabel: { color: '#374151', fontSize: 13, fontWeight: '600', marginBottom: 8, marginTop: 14 },
  titleInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 12,
    borderWidth: 1,
    color: '#111827',
    fontSize: 16,
    padding: 14,
  },
  timeRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  recurrenceToggle: { alignItems: 'center', flexDirection: 'row', gap: 9, marginTop: 18, minHeight: 30 },
  recurrenceLabel: { color: '#34445A', fontSize: 14, fontWeight: '700' },
  timeButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dateButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#E5E7EB',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  timeButtonText: { color: '#2563EB', fontSize: 14, fontWeight: '600' },
  clearTimeButton: { padding: 8 },
  clearTimeText: { color: '#7B8490', fontSize: 13 },
  tagList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagButton: {
    alignItems: 'center',
    borderColor: '#E5E7EB',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  selectedTagButton: { backgroundColor: '#EFF6FF', borderColor: '#93C5FD' },
  tagText: { color: '#6B7280', fontSize: 12 },
  tagIcon: { color: '#4B5563', fontSize: 14, fontWeight: '500' },
  selectedTagText: { color: '#2563EB', fontWeight: '700' },
  errorText: { color: '#B04C4C', fontSize: 13, marginTop: 14 },
  submitButton: {
    alignItems: 'center',
    backgroundColor: '#2563EB',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 22,
    minHeight: 48,
  },
  submitPressed: { backgroundColor: '#1D4ED8' },
  submitText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  editorActions: { alignItems: 'center', flexDirection: 'row', gap: 12, marginTop: 22 },
  deleteButton: {
    alignItems: 'center',
    borderColor: '#FECACA',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  deleteText: { color: '#DC2626', fontSize: 15, fontWeight: '700' },
  saveButton: { flex: 1, marginTop: 0 },
});
