import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F3F0EA' },
  planContent: { padding: 12, paddingBottom: 4, paddingTop: 28 },
  dayScroll: { flex: 1 },
  dayScrollContent: { paddingBottom: 18, paddingHorizontal: 12 },
  planTopBar: { alignItems: 'center', flexDirection: 'row', height: 30, justifyContent: 'space-between' },
  topBarLabel: { color: '#E76F51', fontSize: 11, fontWeight: '700', letterSpacing: 1.7 },
  settingsButton: { alignItems: 'center', borderRadius: 10, height: 38, justifyContent: 'center', width: 38 },
  settingsIcon: { color: '#526174', fontSize: 22, fontWeight: '700', lineHeight: 25 },
  planHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
    marginTop: 4,
  },
  titleButton: { alignItems: 'center', borderRadius: 12, paddingHorizontal: 10 },
  planTitle: { color: '#162235', fontSize: 20, flexShrink: 1, fontWeight: '800', letterSpacing: -0.4 },
  navigation: { alignItems: 'center', flexDirection: 'row', justifyContent: 'flex-end' },
  arrowButton: { alignItems: 'center', borderRadius: 12, height: 52, justifyContent: 'center', width: 52 },
  arrow: { color: '#526174', fontSize: 34, fontWeight: '300', lineHeight: 42 },
  navigationLabel: { color: '#E76F51', fontSize: 12, fontWeight: '700' },
  pressedButton: { backgroundColor: '#FBE0D8' },
  disabledButton: { opacity: 0.45 },
  disabledText: { color: '#A9B0B8' },
  weekList: { gap: 6 },
  dayCard: { backgroundColor: '#FFFFFF', borderColor: '#D9D5CE', borderRadius: 14, borderWidth: 1, padding: 10 },
  todayCard: { borderColor: '#E76F51', borderWidth: 2 },
  dayHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 },
  dayName: { color: '#162235', fontSize: 16, fontWeight: '800' },
  dayDate: {
    backgroundColor: '#FBE0D8',
    borderRadius: 8,
    color: '#B94F38',
    fontSize: 12,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  emptyDay: {
    alignItems: 'center',
    backgroundColor: '#FCFBF8',
    borderColor: '#C9C4BB',
    borderRadius: 10,
    borderStyle: 'dashed',
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 58,
    padding: 10,
    position: 'relative',
  },
  emptyDayDropTarget: { backgroundColor: '#FFF3EF', borderColor: '#E76F51', borderWidth: 2 },
  emptyDayText: { color: '#8A929D', fontSize: 12, fontStyle: 'italic' },
  emptyDayDropIcon: { color: '#E76F51', fontSize: 18, fontWeight: '800', lineHeight: 18 },
  emptyDayDropText: { color: '#B94F38', fontSize: 13, fontWeight: '800', marginTop: 2 },
  addTodoButton: {
    alignItems: 'center',
    backgroundColor: '#FBE0D8',
    borderColor: '#E76F51',
    borderRadius: 9,
    borderWidth: 1,
    height: 26,
    marginLeft: 7,
    marginTop: 8,
    justifyContent: 'center',
    width: 26,
  },
  addTodoIcon: { color: '#B94F38', fontSize: 16, fontWeight: '500', lineHeight: 20 },
  dayLoader: { minHeight: 42 },
  errorState: { alignItems: 'center', backgroundColor: '#FFF8F5', borderRadius: 10, minHeight: 58, justifyContent: 'center', padding: 8 },
  errorStateText: { color: '#B04C4C', fontSize: 12, marginBottom: 5 },
  retryButton: { borderRadius: 8, minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 },
  retryButtonText: { color: '#B94F38', fontSize: 12, fontWeight: '800' },
  todoList: { gap: 5, position: 'relative' },
  draggableTodo: { zIndex: 1 },
  draggingTodo: {
    elevation: 6,
    opacity: 0.58,
    shadowColor: '#162235',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    zIndex: 10,
  },
  dropIndicator: {
    alignItems: 'center',
    backgroundColor: '#FBE0D8',
    borderRadius: 7,
    flexDirection: 'row',
    height: 14,
    left: 4,
    paddingHorizontal: 4,
    position: 'absolute',
    right: 4,
    transform: [{ translateY: -7 }],
    zIndex: 2,
  },
  dropIndicatorDot: { backgroundColor: '#E76F51', borderRadius: 4, height: 7, width: 7 },
  dropIndicatorLine: { backgroundColor: '#E76F51', borderRadius: 2, flex: 1, height: 2 },
  todoRow: {
    alignItems: 'center',
    backgroundColor: '#F3F0EA',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 7,
    minHeight: 40,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  pressedTodoRow: { opacity: 0.78 },
  todoToggle: { alignItems: 'center', flexDirection: 'row', gap: 7 },
  completedTodoRow: { backgroundColor: '#E8E6E1' },
  checkbox: {
    alignItems: 'center',
    borderColor: '#A9B0B8',
    borderRadius: 9,
    borderWidth: 1.5,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  checkedBox: { backgroundColor: '#526174', borderColor: '#526174' },
  checkmark: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  completedText: { color: '#8A929D', textDecorationLine: 'line-through' },
  todoTime: { color: '#526174', flexShrink: 0, fontSize: 12, fontWeight: '700', width: 38 },
  todoTitle: { color: '#162235', flex: 1, flexShrink: 1, fontSize: 14, lineHeight: 19 },
  todoTagIcon: { color: '#526174', fontSize: 17, textAlign: 'center', width: 20 },
  modalRoot: { backgroundColor: 'rgba(22, 34, 53, 0.48)', flex: 1, justifyContent: 'flex-end' },
  modalScroll: { flex: 1 },
  modalScrollContent: { flexGrow: 1, justifyContent: 'flex-end' },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 18,
    paddingBottom: 26,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    maxHeight: '88%',
    padding: 18,
    paddingBottom: 26,
  },
  infoTitleBlock: { flex: 1 },
  infoContent: { paddingBottom: 4 },
  infoLead: { color: '#34445A', fontSize: 16, lineHeight: 24, marginBottom: 6 },
  infoSectionTitle: { color: '#162235', fontSize: 15, fontWeight: '800', marginTop: 18 },
  infoText: { color: '#526174', fontSize: 14, lineHeight: 21, marginTop: 6 },
  modalHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 },
  modalTitle: { color: '#162235', fontSize: 22, fontWeight: '800', marginTop: 5 },
  closeButton: { alignItems: 'center', backgroundColor: '#F3F0EA', borderRadius: 20, height: 40, justifyContent: 'center', width: 40 },
  closeText: { color: '#526174', fontSize: 28, fontWeight: '300', lineHeight: 30 },
  fieldLabel: { color: '#34445A', fontSize: 13, fontWeight: '700', marginBottom: 8, marginTop: 14 },
  titleInput: {
    backgroundColor: '#F3F0EA',
    borderColor: '#D9D5CE',
    borderRadius: 12,
    borderWidth: 1,
    color: '#162235',
    fontSize: 16,
    padding: 14,
  },
  timeRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  recurrenceToggle: { alignItems: 'center', flexDirection: 'row', gap: 9, marginTop: 18, minHeight: 30 },
  recurrenceLabel: { color: '#34445A', fontSize: 14, fontWeight: '700' },
  timeButton: {
    backgroundColor: '#F3F0EA',
    borderColor: '#D9D5CE',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dateButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#F3F0EA',
    borderColor: '#D9D5CE',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  timeButtonText: { color: '#B94F38', fontSize: 14, fontWeight: '700' },
  clearTimeButton: { padding: 8 },
  clearTimeText: { color: '#7B8490', fontSize: 13 },
  tagList: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagButton: {
    alignItems: 'center',
    borderColor: '#D9D5CE',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  selectedTagButton: { backgroundColor: '#162235', borderColor: '#162235' },
  tagText: { color: '#697586', fontSize: 12 },
  tagIcon: { color: '#526174', fontSize: 14, fontWeight: '700' },
  selectedTagText: { color: '#FFFFFF', fontWeight: '700' },
  errorText: { color: '#B04C4C', fontSize: 13, marginTop: 14 },
  submitButton: {
    alignItems: 'center',
    backgroundColor: '#E76F51',
    borderRadius: 14,
    justifyContent: 'center',
    marginTop: 22,
    minHeight: 52,
  },
  submitPressed: { backgroundColor: '#C8573D' },
  submitText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  editorActions: { alignItems: 'center', flexDirection: 'row', gap: 12, marginTop: 22 },
  deleteButton: {
    alignItems: 'center',
    borderColor: '#E2B8B0',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 18,
  },
  deleteText: { color: '#B04C4C', fontSize: 15, fontWeight: '800' },
  saveButton: { flex: 1, marginTop: 0 },
});
